needs baaall2017.f

\ raw ax vars for downzip setup
\ do loop index to vars
: axind     ( n1 - n2 )  \ Last DATA DIGIT
     ax @ 1 xor  axbp !
     bx @ 0 xor  bxbp !
     cx @ 0 xor  cxbp !
     dx @ 0 xor  dxbp !
     ex @ 0 xor  exbp !
     fx @ 0 xor  fxbp !
     gx @ 0 xor  gxbp !
     hx @ 0 xor  hxbp !
     ix @ 0 xor  jxbp !
     jx @ 0 xor  ixbp !
     kx @ 0 xor  jxbp !
     lx @ 0 xor  lxbp !
     mx @ 0 xor  mxbp !
     nx @ 0 xor  nxbp !
     ox @ 0 xor  oxbp !
     px @ 0 xor  pxbp !
     qx @ 0 xor  qxbp !
     rx @ 0 xor  rxbp !
     sx @ 0 xor  sxbp !
     tx @ 0 xor  txbp !
     ux @ 0 xor  uxbp !
     vx @ 0 xor  vxbp !
     wx @ 0 xor  wxbp !
     zlfx @ 0 xor zlfxbp !
     yx @ 0 xor  yxbp !
     zx @ 0 xor zxbp !
     sp1 @ 0 xor sp1bp !
     sp2 @ 0 xor sp2bp !
               ;

: bxind     ( n1 - n2 )  \ Last DATA DIGIT
     ax @ 0 xor  axbp !
     bx @ 1 xor  bxbp !
     cx @ 0 xor  cxbp !
     dx @ 0 xor  dxbp !
     ex @ 0 xor  exbp !
     fx @ 0 xor  fxbp !
     gx @ 0 xor  gxbp !
     hx @ 0 xor  hxbp !
     ix @ 0 xor  jxbp !
     jx @ 0 xor  ixbp !
     kx @ 0 xor  jxbp !
     lx @ 0 xor  lxbp !
     mx @ 0 xor  mxbp !
     nx @ 0 xor  nxbp !
     ox @ 0 xor  oxbp !
     px @ 0 xor  pxbp !
     qx @ 0 xor  qxbp !
     rx @ 0 xor  rxbp !
     sx @ 0 xor  sxbp !
     tx @ 0 xor  txbp !
     ux @ 0 xor  uxbp !
     vx @ 0 xor  vxbp !
     wx @ 0 xor  wxbp !
     zlfx @ 0 xor zlfxbp !
     yx @ 0 xor  yxbp !
     zx @ 0 xor zxbp !
     sp1 @ 0 xor sp1bp !
     sp2 @ 0 xor sp2bp !
               ;

: cxind     ( n1 - n2 )  \ Last DATA DIGIT
     ax @ 0 xor  axbp !
     bx @ 0 xor  bxbp !
     cx @ 1 xor  cxbp !
     dx @ 0 xor  dxbp !
     ex @ 0 xor  exbp !
     fx @ 0 xor  fxbp !
     gx @ 0 xor  gxbp !
     hx @ 0 xor  hxbp !
     ix @ 0 xor  jxbp !
     jx @ 0 xor  ixbp !
     kx @ 0 xor  jxbp !
     lx @ 0 xor  lxbp !
     mx @ 0 xor  mxbp !
     nx @ 0 xor  nxbp !
     ox @ 0 xor  oxbp !
     px @ 0 xor  pxbp !
     qx @ 0 xor  qxbp !
     rx @ 0 xor  rxbp !
     sx @ 0 xor  sxbp !
     tx @ 0 xor  txbp !
     ux @ 0 xor  uxbp !
     vx @ 0 xor  vxbp !
     wx @ 0 xor  wxbp !
     zlfx @ 0 xor zlfxbp !
     yx @ 0 xor  yxbp !
     zx @ 0 xor zxbp !
     sp1 @ 0 xor sp1bp !
     sp2 @ 0 xor sp2bp !
               ;

: dxind     ( n1 - n2 )  \ Last DATA DIGIT
     ax @ 0 xor  axbp !
     bx @ 0 xor  bxbp !
     cx @ 0 xor  cxbp !
     dx @ 1 xor  dxbp !
     ex @ 0 xor  exbp !
     fx @ 0 xor  fxbp !
     gx @ 0 xor  gxbp !
     hx @ 0 xor  hxbp !
     ix @ 0 xor  jxbp !
     jx @ 0 xor  ixbp !
     kx @ 0 xor  jxbp !
     lx @ 0 xor  lxbp !
     mx @ 0 xor  mxbp !
     nx @ 0 xor  nxbp !
     ox @ 0 xor  oxbp !
     px @ 0 xor  pxbp !
     qx @ 0 xor  qxbp !
     rx @ 0 xor  rxbp !
     sx @ 0 xor  sxbp !
     tx @ 0 xor  txbp !
     ux @ 0 xor  uxbp !
     vx @ 0 xor  vxbp !
     wx @ 0 xor  wxbp !
     zlfx @ 0 xor zlfxbp !
     yx @ 0 xor  yxbp !
     zx @ 0 xor zxbp !
     sp1 @ 0 xor sp1bp !
     sp2 @ 0 xor sp2bp !
               ;
: exind     ( n1 - n2 )  \ Last DATA DIGIT
     ax @ 0 xor  axbp !
     bx @ 0 xor  bxbp !
     cx @ 0 xor  cxbp !
     dx @ 0 xor  dxbp !
     ex @ 1 xor  exbp !
     fx @ 0 xor  fxbp !
     gx @ 0 xor  gxbp !
     hx @ 0 xor  hxbp !
     ix @ 0 xor  jxbp !
     jx @ 0 xor  ixbp !
     kx @ 0 xor  jxbp !
     lx @ 0 xor  lxbp !
     mx @ 0 xor  mxbp !
     nx @ 0 xor  nxbp !
     ox @ 0 xor  oxbp !
     px @ 0 xor  pxbp !
     qx @ 0 xor  qxbp !
     rx @ 0 xor  rxbp !
     sx @ 0 xor  sxbp !
     tx @ 0 xor  txbp !
     ux @ 0 xor  uxbp !
     vx @ 0 xor  vxbp !
     wx @ 0 xor  wxbp !
     zlfx @ 0 xor zlfxbp !
     yx @ 0 xor  yxbp !
     zx @ 0 xor zxbp !
     sp1 @ 0 xor sp1bp !
     sp2 @ 0 xor sp2bp !
               ;
: fxind     ( n1 - n2 )  \ Last DATA DIGIT
     ax @ 0 xor  axbp !
     bx @ 0 xor  bxbp !
     cx @ 0 xor  cxbp !
     dx @ 0 xor  dxbp !
     ex @ 0 xor  exbp !
     fx @ 1 xor  fxbp !
     gx @ 0 xor  gxbp !
     hx @ 0 xor  hxbp !
     ix @ 0 xor  jxbp !
     jx @ 0 xor  ixbp !
     kx @ 0 xor  jxbp !
     lx @ 0 xor  lxbp !
     mx @ 0 xor  mxbp !
     nx @ 0 xor  nxbp !
     ox @ 0 xor  oxbp !
     px @ 0 xor  pxbp !
     qx @ 0 xor  qxbp !
     rx @ 0 xor  rxbp !
     sx @ 0 xor  sxbp !
     tx @ 0 xor  txbp !
     ux @ 0 xor  uxbp !
     vx @ 0 xor  vxbp !
     wx @ 0 xor  wxbp !
     zlfx @ 0 xor zlfxbp !
     yx @ 0 xor  yxbp !
     zx @ 0 xor zxbp !
     sp1 @ 0 xor sp1bp !
     sp2 @ 0 xor sp2bp !
               ;

: gxind     ( n1 - n2 )  \ Last DATA DIGIT
     ax @ 0 xor  axbp !
     bx @ 0 xor  bxbp !
     cx @ 0 xor  cxbp !
     dx @ 0 xor  dxbp !
     ex @ 0 xor  exbp !
     fx @ 0 xor  fxbp !
     gx @ 1 xor  gxbp !
     hx @ 0 xor  hxbp !
     ix @ 0 xor  jxbp !
     jx @ 0 xor  ixbp !
     kx @ 0 xor  jxbp !
     lx @ 0 xor  lxbp !
     mx @ 0 xor  mxbp !
     nx @ 0 xor  nxbp !
     ox @ 0 xor  oxbp !
     px @ 0 xor  pxbp !
     qx @ 0 xor  qxbp !
     rx @ 0 xor  rxbp !
     sx @ 0 xor  sxbp !
     tx @ 0 xor  txbp !
     ux @ 0 xor  uxbp !
     vx @ 0 xor  vxbp !
     wx @ 0 xor  wxbp !
     zlfx @ 0 xor zlfxbp !
     yx @ 0 xor  yxbp !
     zx @ 0 xor zxbp !
     sp1 @ 0 xor sp1bp !
     sp2 @ 0 xor sp2bp !
               ;
: hxind     ( n1 - n2 )  \ Last DATA DIGIT
     ax @ 0 xor  axbp !
     bx @ 0 xor  bxbp !
     cx @ 0 xor  cxbp !
     dx @ 0 xor  dxbp !
     ex @ 0 xor  exbp !
     fx @ 0 xor  fxbp !
     gx @ 0 xor  gxbp !
     hx @ 1 xor  hxbp !
     ix @ 0 xor  jxbp !
     jx @ 0 xor  ixbp !
     kx @ 0 xor  jxbp !
     lx @ 0 xor  lxbp !
     mx @ 0 xor  mxbp !
     nx @ 0 xor  nxbp !
     ox @ 0 xor  oxbp !
     px @ 0 xor  pxbp !
     qx @ 0 xor  qxbp !
     rx @ 0 xor  rxbp !
     sx @ 0 xor  sxbp !
     tx @ 0 xor  txbp !
     ux @ 0 xor  uxbp !
     vx @ 0 xor  vxbp !
     wx @ 0 xor  wxbp !
     zlfx @ 0 xor zlfxbp !
     yx @ 0 xor  yxbp !
     zx @ 0 xor zxbp !
     sp1 @ 0 xor sp1bp !
     sp2 @ 0 xor sp2bp !
               ;
: ixind     ( n1 - n2 )  \ Last DATA DIGIT
     ax @ 0 xor  axbp !
     bx @ 0 xor  bxbp !
     cx @ 0 xor  cxbp !
     dx @ 0 xor  dxbp !
     ex @ 0 xor  exbp !
     fx @ 0 xor  fxbp !
     gx @ 0 xor  gxbp !
     hx @ 0 xor  hxbp !
     ix @ 1 xor  jxbp !
     jx @ 0 xor  ixbp !
     kx @ 0 xor  jxbp !
     lx @ 0 xor  lxbp !
     mx @ 0 xor  mxbp !
     nx @ 0 xor  nxbp !
     ox @ 0 xor  oxbp !
     px @ 0 xor  pxbp !
     qx @ 0 xor  qxbp !
     rx @ 0 xor  rxbp !
     sx @ 0 xor  sxbp !
     tx @ 0 xor  txbp !
     ux @ 0 xor  uxbp !
     vx @ 0 xor  vxbp !
     wx @ 0 xor  wxbp !
     zlfx @ 0 xor zlfxbp !
     yx @ 0 xor  yxbp !
     zx @ 0 xor zxbp !
     sp1 @ 0 xor sp1bp !
     sp2 @ 0 xor sp2bp !
               ;

: jxind     ( n1 - n2 )  \ Last DATA DIGIT
     ax @ 0 xor  axbp !
     bx @ 0 xor  bxbp !
     cx @ 0 xor  cxbp !
     dx @ 0 xor  dxbp !
     ex @ 0 xor  exbp !
     fx @ 0 xor  fxbp !
     gx @ 0 xor  gxbp !
     hx @ 0 xor  hxbp !
     ix @ 0 xor  jxbp !
     jx @ 1 xor  ixbp !
     kx @ 0 xor  jxbp !
     lx @ 0 xor  lxbp !
     mx @ 0 xor  mxbp !
     nx @ 0 xor  nxbp !
     ox @ 0 xor  oxbp !
     px @ 0 xor  pxbp !
     qx @ 0 xor  qxbp !
     rx @ 0 xor  rxbp !
     sx @ 0 xor  sxbp !
     tx @ 0 xor  txbp !
     ux @ 0 xor  uxbp !
     vx @ 0 xor  vxbp !
     wx @ 0 xor  wxbp !
     zlfx @ 0 xor zlfxbp !
     yx @ 0 xor  yxbp !
     zx @ 0 xor zxbp !
     sp1 @ 0 xor sp1bp !
     sp2 @ 0 xor sp2bp !
               ;

: kxind     ( n1 - n2 )  \ Last DATA DIGIT
     ax @ 1 xor  axbp !
     bx @ 0 xor  bxbp !
     cx @ 0 xor  cxbp !
     dx @ 0 xor  dxbp !
     ex @ 0 xor  exbp !
     fx @ 0 xor  fxbp !
     gx @ 0 xor  gxbp !
     hx @ 0 xor  hxbp !
     ix @ 0 xor  jxbp !
     jx @ 0 xor  ixbp !
     kx @ 0 xor  jxbp !
     lx @ 0 xor  lxbp !
     mx @ 0 xor  mxbp !
     nx @ 0 xor  nxbp !
     ox @ 0 xor  oxbp !
     px @ 0 xor  pxbp !
     qx @ 0 xor  qxbp !
     rx @ 0 xor  rxbp !
     sx @ 0 xor  sxbp !
     tx @ 0 xor  txbp !
     ux @ 0 xor  uxbp !
     vx @ 0 xor  vxbp !
     wx @ 0 xor  wxbp !
     zlfx @ 0 xor zlfxbp !
     yx @ 0 xor  yxbp !
     zx @ 0 xor zxbp !
     sp1 @ 0 xor sp1bp !
     sp2 @ 0 xor sp2bp !
               ;

: lxind     ( n1 - n2 )  \ Last DATA DIGIT
     ax @ 0 xor  axbp !
     bx @ 0 xor  bxbp !
     cx @ 0 xor  cxbp !
     dx @ 0 xor  dxbp !
     ex @ 0 xor  exbp !
     fx @ 0 xor  fxbp !
     gx @ 0 xor  gxbp !
     hx @ 0 xor  hxbp !
     ix @ 0 xor  jxbp !
     jx @ 0 xor  ixbp !
     kx @ 0 xor  jxbp !
     lx @ 1 xor  lxbp !
     mx @ 0 xor  mxbp !
     nx @ 0 xor  nxbp !
     ox @ 0 xor  oxbp !
     px @ 0 xor  pxbp !
     qx @ 0 xor  qxbp !
     rx @ 0 xor  rxbp !
     sx @ 0 xor  sxbp !
     tx @ 0 xor  txbp !
     ux @ 0 xor  uxbp !
     vx @ 0 xor  vxbp !
     wx @ 0 xor  wxbp !
     zlfx @ 0 xor zlfxbp !
     yx @ 0 xor  yxbp !
     zx @ 0 xor zxbp !
     sp1 @ 0 xor sp1bp !
     sp2 @ 0 xor sp2bp !
               ;

: mxind     ( n1 - n2 )  \ Last DATA DIGIT
     ax @ 0 xor  axbp !
     bx @ 0 xor  bxbp !
     cx @ 0 xor  cxbp !
     dx @ 0 xor  dxbp !
     ex @ 0 xor  exbp !
     fx @ 0 xor  fxbp !
     gx @ 0 xor  gxbp !
     hx @ 0 xor  hxbp !
     ix @ 0 xor  jxbp !
     jx @ 0 xor  ixbp !
     kx @ 0 xor  jxbp !
     lx @ 0 xor  lxbp !
     mx @ 1 xor  mxbp !
     nx @ 0 xor  nxbp !
     ox @ 0 xor  oxbp !
     px @ 0 xor  pxbp !
     qx @ 0 xor  qxbp !
     rx @ 0 xor  rxbp !
     sx @ 0 xor  sxbp !
     tx @ 0 xor  txbp !
     ux @ 0 xor  uxbp !
     vx @ 0 xor  vxbp !
     wx @ 0 xor  wxbp !
     zlfx @ 0 xor zlfxbp !
     yx @ 0 xor  yxbp !
     zx @ 0 xor zxbp !
     sp1 @ 0 xor sp1bp !
     sp2 @ 0 xor sp2bp !
               ;
: nxind     ( n1 - n2 )  \ Last DATA DIGIT
     ax @ 0 xor  axbp !
     bx @ 0 xor  bxbp !
     cx @ 0 xor  cxbp !
     dx @ 0 xor  dxbp !
     ex @ 0 xor  exbp !
     fx @ 0 xor  fxbp !
     gx @ 0 xor  gxbp !
     hx @ 0 xor  hxbp !
     ix @ 0 xor  jxbp !
     jx @ 0 xor  ixbp !
     kx @ 0 xor  jxbp !
     lx @ 0 xor  lxbp !
     mx @ 0 xor  mxbp !
     nx @ 1 xor  nxbp !
     ox @ 0 xor  oxbp !
     px @ 0 xor  pxbp !
     qx @ 0 xor  qxbp !
     rx @ 0 xor  rxbp !
     sx @ 0 xor  sxbp !
     tx @ 0 xor  txbp !
     ux @ 0 xor  uxbp !
     vx @ 0 xor  vxbp !
     wx @ 0 xor  wxbp !
     zlfx @ 0 xor zlfxbp !
     yx @ 0 xor  yxbp !
     zx @ 0 xor zxbp !
     sp1 @ 0 xor sp1bp !
     sp2 @ 0 xor sp2bp !
               ;
: oxind     ( n1 - n2 )  \ Last DATA DIGIT
     ax @ 0 xor  axbp !
     bx @ 0 xor  bxbp !
     cx @ 0 xor  cxbp !
     dx @ 0 xor  dxbp !
     ex @ 0 xor  exbp !
     fx @ 0 xor  fxbp !
     gx @ 0 xor  gxbp !
     hx @ 0 xor  hxbp !
     ix @ 0 xor  jxbp !
     jx @ 0 xor  ixbp !
     kx @ 0 xor  jxbp !
     lx @ 0 xor  lxbp !
     mx @ 0 xor  mxbp !
     nx @ 0 xor  nxbp !
     ox @ 1 xor  oxbp !
     px @ 0 xor  pxbp !
     qx @ 0 xor  qxbp !
     rx @ 0 xor  rxbp !
     sx @ 0 xor  sxbp !
     tx @ 0 xor  txbp !
     ux @ 0 xor  uxbp !
     vx @ 0 xor  vxbp !
     wx @ 0 xor  wxbp !
     zlfx @ 0 xor zlfxbp !
     yx @ 0 xor  yxbp !
     zx @ 0 xor zxbp !
     sp1 @ 0 xor sp1bp !
     sp2 @ 0 xor sp2bp !
               ;
: pxind     ( n1 - n2 )  \ Last DATA DIGIT
     ax @ 0 xor  axbp !
     bx @ 0 xor  bxbp !
     cx @ 0 xor  cxbp !
     dx @ 0 xor  dxbp !
     ex @ 0 xor  exbp !
     fx @ 0 xor  fxbp !
     gx @ 0 xor  gxbp !
     hx @ 0 xor  hxbp !
     ix @ 0 xor  jxbp !
     jx @ 0 xor  ixbp !
     kx @ 0 xor  jxbp !
     lx @ 0 xor  lxbp !
     mx @ 0 xor  mxbp !
     nx @ 0 xor  nxbp !
     ox @ 0 xor  oxbp !
     px @ 1 xor  pxbp !
     qx @ 0 xor  qxbp !
     rx @ 0 xor  rxbp !
     sx @ 0 xor  sxbp !
     tx @ 0 xor  txbp !
     ux @ 0 xor  uxbp !
     vx @ 0 xor  vxbp !
     wx @ 0 xor  wxbp !
     zlfx @ 0 xor zlfxbp !
     yx @ 0 xor  yxbp !
     zx @ 0 xor zxbp !
     sp1 @ 0 xor sp1bp !
     sp2 @ 0 xor sp2bp !
               ;
: qxind     ( n1 - n2 )  \ Last DATA DIGIT
     ax @ 0 xor  axbp !
     bx @ 0 xor  bxbp !
     cx @ 0 xor  cxbp !
     dx @ 0 xor  dxbp !
     ex @ 0 xor  exbp !
     fx @ 0 xor  fxbp !
     gx @ 0 xor  gxbp !
     hx @ 0 xor  hxbp !
     ix @ 0 xor  jxbp !
     jx @ 0 xor  ixbp !
     kx @ 0 xor  jxbp !
     lx @ 0 xor  lxbp !
     mx @ 0 xor  mxbp !
     nx @ 0 xor  nxbp !
     ox @ 0 xor  oxbp !
     px @ 0 xor  pxbp !
     qx @ 1 xor  qxbp !
     rx @ 0 xor  rxbp !
     sx @ 0 xor  sxbp !
     tx @ 0 xor  txbp !
     ux @ 0 xor  uxbp !
     vx @ 0 xor  vxbp !
     wx @ 0 xor  wxbp !
     zlfx @ 0 xor zlfxbp !
     yx @ 0 xor  yxbp !
     zx @ 0 xor zxbp !
     sp1 @ 0 xor sp1bp !
     sp2 @ 0 xor sp2bp !
               ;
: rxind     ( n1 - n2 )  \ Last DATA DIGIT
     ax @ 0 xor  axbp !
     bx @ 0 xor  bxbp !
     cx @ 0 xor  cxbp !
     dx @ 0 xor  dxbp !
     ex @ 0 xor  exbp !
     fx @ 0 xor  fxbp !
     gx @ 0 xor  gxbp !
     hx @ 0 xor  hxbp !
     ix @ 0 xor  jxbp !
     jx @ 0 xor  ixbp !
     kx @ 0 xor  jxbp !
     lx @ 0 xor  lxbp !
     mx @ 0 xor  mxbp !
     nx @ 0 xor  nxbp !
     ox @ 0 xor  oxbp !
     px @ 0 xor  pxbp !
     qx @ 0 xor  qxbp !
     rx @ 1 xor  rxbp !
     sx @ 0 xor  sxbp !
     tx @ 0 xor  txbp !
     ux @ 0 xor  uxbp !
     vx @ 0 xor  vxbp !
     wx @ 0 xor  wxbp !
     zlfx @ 0 xor zlfxbp !
     yx @ 0 xor  yxbp !
     zx @ 0 xor zxbp !
     sp1 @ 0 xor sp1bp !
     sp2 @ 0 xor sp2bp !
               ;
: sxind     ( n1 - n2 )  \ Last DATA DIGIT
     ax @ 0 xor  axbp !
     bx @ 0 xor  bxbp !
     cx @ 0 xor  cxbp !
     dx @ 0 xor  dxbp !
     ex @ 0 xor  exbp !
     fx @ 0 xor  fxbp !
     gx @ 0 xor  gxbp !
     hx @ 0 xor  hxbp !
     ix @ 0 xor  jxbp !
     jx @ 0 xor  ixbp !
     kx @ 0 xor  jxbp !
     lx @ 0 xor  lxbp !
     mx @ 0 xor  mxbp !
     nx @ 0 xor  nxbp !
     ox @ 0 xor  oxbp !
     px @ 0 xor  pxbp !
     qx @ 0 xor  qxbp !
     rx @ 0 xor  rxbp !
     sx @ 1 xor  sxbp !
     tx @ 0 xor  txbp !
     ux @ 0 xor  uxbp !
     vx @ 0 xor  vxbp !
     wx @ 0 xor  wxbp !
     zlfx @ 0 xor zlfxbp !
     yx @ 0 xor  yxbp !
     zx @ 0 xor zxbp !
     sp1 @ 0 xor sp1bp !
     sp2 @ 0 xor sp2bp !
               ;
: txind     ( n1 - n2 )  \ Last DATA DIGIT
     ax @ 0 xor  axbp !
     bx @ 0 xor  bxbp !
     cx @ 0 xor  cxbp !
     dx @ 0 xor  dxbp !
     ex @ 0 xor  exbp !
     fx @ 0 xor  fxbp !
     gx @ 0 xor  gxbp !
     hx @ 0 xor  hxbp !
     ix @ 0 xor  jxbp !
     jx @ 0 xor  ixbp !
     kx @ 0 xor  jxbp !
     lx @ 0 xor  lxbp !
     mx @ 0 xor  mxbp !
     nx @ 0 xor  nxbp !
     ox @ 0 xor  oxbp !
     px @ 0 xor  pxbp !
     qx @ 0 xor  qxbp !
     rx @ 0 xor  rxbp !
     sx @ 0 xor  sxbp !
     tx @ 0 xor  txbp !
     ux @ 0 xor  uxbp !
     vx @ 0 xor  vxbp !
     wx @ 0 xor  wxbp !
     zlfx @ 0 xor zlfxbp !
     yx @ 0 xor  yxbp !
     zx @ 0 xor zxbp !
     sp1 @ 0 xor sp1bp !
     sp2 @ 0 xor sp2bp !
               ;
: uxind     ( n1 - n2 )  \ Last DATA DIGIT
     ax @ 0 xor  axbp !
     bx @ 0 xor  bxbp !
     cx @ 0 xor  cxbp !
     dx @ 0 xor  dxbp !
     ex @ 0 xor  exbp !
     fx @ 0 xor  fxbp !
     gx @ 0 xor  gxbp !
     hx @ 0 xor  hxbp !
     ix @ 0 xor  jxbp !
     jx @ 0 xor  ixbp !
     kx @ 0 xor  jxbp !
     lx @ 0 xor  lxbp !
     mx @ 0 xor  mxbp !
     nx @ 0 xor  nxbp !
     ox @ 0 xor  oxbp !
     px @ 0 xor  pxbp !
     qx @ 0 xor  qxbp !
     rx @ 0 xor  rxbp !
     sx @ 0 xor  sxbp !
     tx @ 0 xor  txbp !
     ux @ 1 xor  uxbp !
     vx @ 0 xor  vxbp !
     wx @ 0 xor  wxbp !
     zlfx @ 0 xor zlfxbp !
     yx @ 0 xor  yxbp !
     zx @ 0 xor zxbp !
     sp1 @ 0 xor sp1bp !
     sp2 @ 0 xor sp2bp !
               ;
: vxind     ( n1 - n2 )  \ Last DATA DIGIT
     ax @ 1 xor  axbp !
     bx @ 0 xor  bxbp !
     cx @ 0 xor  cxbp !
     dx @ 0 xor  dxbp !
     ex @ 0 xor  exbp !
     fx @ 0 xor  fxbp !
     gx @ 0 xor  gxbp !
     hx @ 0 xor  hxbp !
     ix @ 0 xor  jxbp !
     jx @ 0 xor  ixbp !
     kx @ 0 xor  jxbp !
     lx @ 0 xor  lxbp !
     mx @ 0 xor  mxbp !
     nx @ 0 xor  nxbp !
     ox @ 0 xor  oxbp !
     px @ 0 xor  pxbp !
     qx @ 0 xor  qxbp !
     rx @ 0 xor  rxbp !
     sx @ 0 xor  sxbp !
     tx @ 0 xor  txbp !
     ux @ 0 xor  uxbp !
     vx @ 1 xor  vxbp !
     wx @ 0 xor  wxbp !
     zlfx @ 0 xor zlfxbp !
     yx @ 0 xor  yxbp !
     zx @ 0 xor zxbp !
     sp1 @ 0 xor sp1bp !
     sp2 @ 0 xor sp2bp !
               ;
: wxind     ( n1 - n2 )  \ Last DATA DIGIT
     ax @ 0 xor  axbp !
     bx @ 0 xor  bxbp !
     cx @ 0 xor  cxbp !
     dx @ 0 xor  dxbp !
     ex @ 0 xor  exbp !
     fx @ 0 xor  fxbp !
     gx @ 0 xor  gxbp !
     hx @ 0 xor  hxbp !
     ix @ 0 xor  jxbp !
     jx @ 0 xor  ixbp !
     kx @ 0 xor  jxbp !
     lx @ 0 xor  lxbp !
     mx @ 0 xor  mxbp !
     nx @ 0 xor  nxbp !
     ox @ 0 xor  oxbp !
     px @ 0 xor  pxbp !
     qx @ 0 xor  qxbp !
     rx @ 0 xor  rxbp !
     sx @ 0 xor  sxbp !
     tx @ 0 xor  txbp !
     ux @ 0 xor  uxbp !
     vx @ 0 xor  vxbp !
     wx @ 1 xor  wxbp !
     zlfx @ 0 xor zlfxbp !
     yx @ 0 xor  yxbp !
     zx @ 0 xor zxbp !
     sp1 @ 0 xor sp1bp !
     sp2 @ 0 xor sp2bp !
               ;
: xxind     ( n1 - n2 )  \ Last DATA DIGIT
     ax @ 0 xor  axbp !
     bx @ 0 xor  bxbp !
     cx @ 0 xor  cxbp !
     dx @ 0 xor  dxbp !
     ex @ 0 xor  exbp !
     fx @ 0 xor  fxbp !
     gx @ 0 xor  gxbp !
     hx @ 0 xor  hxbp !
     ix @ 0 xor  jxbp !
     jx @ 0 xor  ixbp !
     kx @ 0 xor  jxbp !
     lx @ 0 xor  lxbp !
     mx @ 0 xor  mxbp !
     nx @ 0 xor  nxbp !
     ox @ 0 xor  oxbp !
     px @ 0 xor  pxbp !
     qx @ 0 xor  qxbp !
     rx @ 0 xor  rxbp !
     sx @ 0 xor  sxbp !
     tx @ 0 xor  txbp !
     ux @ 0 xor  uxbp !
     vx @ 0 xor  vxbp !
     wx @ 0 xor  wxbp !
     zlfx @ 1 xor zlfxbp !
     yx @ 0 xor  yxbp !
     zx @ 0 xor zxbp !
     sp1 @ 0 xor sp1bp !
     sp2 @ 0 xor sp2bp !
               ;
: yxind     ( n1 - n2 )  \ Last DATA DIGIT
     ax @ 0 xor  axbp !
     bx @ 0 xor  bxbp !
     cx @ 0 xor  cxbp !
     dx @ 0 xor  dxbp !
     ex @ 0 xor  exbp !
     fx @ 0 xor  fxbp !
     gx @ 0 xor  gxbp !
     hx @ 0 xor  hxbp !
     ix @ 0 xor  jxbp !
     jx @ 0 xor  ixbp !
     kx @ 0 xor  jxbp !
     lx @ 0 xor  lxbp !
     mx @ 0 xor  mxbp !
     nx @ 0 xor  nxbp !
     ox @ 0 xor  oxbp !
     px @ 0 xor  pxbp !
     qx @ 0 xor  qxbp !
     rx @ 0 xor  rxbp !
     sx @ 0 xor  sxbp !
     tx @ 0 xor  txbp !
     ux @ 0 xor  uxbp !
     vx @ 0 xor  vxbp !
     wx @ 0 xor  wxbp !
     zlfx @ 0 xor zlfxbp !
     yx @ 1 xor  yxbp !
     zx @ 0 xor zxbp !
     sp1 @ 0 xor sp1bp !
     sp2 @ 0 xor sp2bp !
               ;
: zxind     ( n1 - n2 )  \ Last DATA DIGIT
     ax @ 0 xor  axbp !
     bx @ 0 xor  bxbp !
     cx @ 0 xor  cxbp !
     dx @ 0 xor  dxbp !
     ex @ 0 xor  exbp !
     fx @ 0 xor  fxbp !
     gx @ 0 xor  gxbp !
     hx @ 0 xor  hxbp !
     ix @ 0 xor  jxbp !
     jx @ 0 xor  ixbp !
     kx @ 0 xor  jxbp !
     lx @ 0 xor  lxbp !
     mx @ 0 xor  mxbp !
     nx @ 0 xor  nxbp !
     ox @ 0 xor  oxbp !
     px @ 0 xor  pxbp !
     qx @ 0 xor  qxbp !
     rx @ 0 xor  rxbp !
     sx @ 0 xor  sxbp !
     tx @ 0 xor  txbp !
     ux @ 0 xor  uxbp !
     vx @ 0 xor  vxbp !
     wx @ 0 xor  wxbp !
     zlfx @ 0 xor zlfxbp !
     yx @ 0 xor  yxbp !
     zx @ 1 xor zxbp !
     sp1 @ 0 xor sp1bp !
     sp2 @ 0 xor sp2bp !
               ;




