needs testbaall.f
needs baaall2017.f
: axx1     ( n1 - n2 )  \ Last DATA DIGIT
     xad @ 1 xor  xad !
     xbd @ 0 xor  xbd !
     xcd @ 0 xor  xcd !
     xdd @ 0 xor  xdd !
     xed @ 0 xor  xed !
     xfd @ 0 xor  xfd !
     xgd @ 0 xor  xgd !
     xhd @ 0 xor  xhd !
     xid @ 0 xor  xid !
     xjd @ 0 xor  xjd !
     xkd @ 0 xor  xkd !
     xld @ 0 xor  xld !
     xmd @ 0 xor  xmd !
     xnd @ 0 xor  xnd !
     xod @ 0 xor  xod !
     xpd @ 0 xor  xpd !
     xqd @ 0 xor  xqd !
     xrd @ 0 xor  xrd !
     xsd @ 0 xor  xsd !
     xtd @ 0 xor  xtd !
     xud @ 0 xor  xud !
     xvd @ 0 xor  xvd !
     xwd @ 0 xor  xwd !
     xxd @ 0 xor xxd !
     xyd @ 0 xor  xyd !
     xzd @ 0 xor xzd !
     sp1x @ 0 xor sp1x !
     sp2x @ 0 xor sp2x !
               ;
: bxx1     ( n1 - n2 )  \ Last DATA DIGIT
     xad @ 0 xor  xad !
     xbd @ 1 xor  xbd !
     xcd @ 0 xor  xcd !
     xdd @ 0 xor  xdd !
     xed @ 0 xor  xed !
     xfd @ 0 xor  xfd !
     xgd @ 0 xor  xgd !
     xhd @ 0 xor  xhd !
     xid @ 0 xor  xid !
     xjd @ 0 xor  xjd !
     xkd @ 0 xor  xkd !
     xld @ 0 xor  xld !
     xmd @ 0 xor  xmd !
     xnd @ 0 xor  xnd !
     xod @ 0 xor  xod !
     xpd @ 0 xor  xpd !
     xqd @ 0 xor  xqd !
     xrd @ 0 xor  xrd !
     xsd @ 0 xor  xsd !
     xtd @ 0 xor  xtd !
     xud @ 0 xor  xud !
     xvd @ 0 xor  xvd !
     xwd @ 0 xor  xwd !
     xxd @ 0 xor xxd !
     xyd @ 0 xor  xyd !
     xzd @ 0 xor xzd !
     sp1x @ 0 xor sp1x !
     sp2x @ 0 xor sp2x !
               ;
: cxx1     ( n1 - n2 )  \ Last DATA DIGIT
     xad @ 0 xor  xad !
     xbd @ 0 xor  xbd !
     xcd @ 1 xor  xcd !
     xdd @ 0 xor  xdd !
     xed @ 0 xor  xed !
     xfd @ 0 xor  xfd !
     xgd @ 0 xor  xgd !
     xhd @ 0 xor  xhd !
     xid @ 0 xor  xid !
     xjd @ 0 xor  xjd !
     xkd @ 0 xor  xkd !
     xld @ 0 xor  xld !
     xmd @ 0 xor  xmd !
     xnd @ 0 xor  xnd !
     xod @ 0 xor  xod !
     xpd @ 0 xor  xpd !
     xqd @ 0 xor  xqd !
     xrd @ 0 xor  xrd !
     xsd @ 0 xor  xsd !
     xtd @ 0 xor  xtd !
     xud @ 0 xor  xud !
     xvd @ 0 xor  xvd !
     xwd @ 0 xor  xwd !
     xxd @ 0 xor xxd !
     xyd @ 0 xor  xyd !
     xzd @ 0 xor xzd !
     sp1x @ 0 xor sp1x !
     sp2x @ 0 xor sp2x !
               ;
: dxx1     ( n1 - n2 )  \ Last DATA DIGIT
     xad @ 0 xor  xad !
     xbd @ 0 xor  xbd !
     xcd @ 0 xor  xcd !
     xdd @ 1 xor  xdd !
     xed @ 0 xor  xed !
     xfd @ 0 xor  xfd !
     xgd @ 0 xor  xgd !
     xhd @ 0 xor  xhd !
     xid @ 0 xor  xid !
     xjd @ 0 xor  xjd !
     xkd @ 0 xor  xkd !
     xld @ 0 xor  xld !
     xmd @ 0 xor  xmd !
     xnd @ 0 xor  xnd !
     xod @ 0 xor  xod !
     xpd @ 0 xor  xpd !
     xqd @ 0 xor  xqd !
     xrd @ 0 xor  xrd !
     xsd @ 0 xor  xsd !
     xtd @ 0 xor  xtd !
     xud @ 0 xor  xud !
     xvd @ 0 xor  xvd !
     xwd @ 0 xor  xwd !
     xxd @ 0 xor xxd !
     xyd @ 0 xor  xyd !
     xzd @ 0 xor xzd !
     sp1x @ 0 xor sp1x !
     sp2x @ 0 xor sp2x !
               ;
: exx1    ( n1 - n2 )  \ Last DATA DIGIT
     xad @ 0 xor  xad !
     xbd @ 0 xor  xbd !
     xcd @ 0 xor  xcd !
     xdd @ 0 xor  xdd !
     xed @ 1 xor  xed !
     xfd @ 0 xor  xfd !
     xgd @ 0 xor  xgd !
     xhd @ 0 xor  xhd !
     xid @ 0 xor  xid !
     xjd @ 0 xor  xjd !
     xkd @ 0 xor  xkd !
     xld @ 0 xor  xld !
     xmd @ 0 xor  xmd !
     xnd @ 0 xor  xnd !
     xod @ 0 xor  xod !
     xpd @ 0 xor  xpd !
     xqd @ 0 xor  xqd !
     xrd @ 0 xor  xrd !
     xsd @ 0 xor  xsd !
     xtd @ 0 xor  xtd !
     xud @ 0 xor  xud !
     xvd @ 0 xor  xvd !
     xwd @ 0 xor  xwd !
     xxd @ 0 xor xxd !
     xyd @ 0 xor  xyd !
     xzd @ 0 xor xzd !
     sp1x @ 0 xor sp1x !
     sp2x @ 0 xor sp2x !
               ;
: fxx1     ( n1 - n2 )  \ Last DATA DIGIT
     xad @ 0 xor  xad !
     xbd @ 0 xor  xbd !
     xcd @ 0 xor  xcd !
     xdd @ 0 xor  xdd !
     xed @ 0 xor  xed !
     xfd @ 1 xor  xfd !
     xgd @ 0 xor  xgd !
     xhd @ 0 xor  xhd !
     xid @ 0 xor  xid !
     xjd @ 0 xor  xjd !
     xkd @ 0 xor  xkd !
     xld @ 0 xor  xld !
     xmd @ 0 xor  xmd !
     xnd @ 0 xor  xnd !
     xod @ 0 xor  xod !
     xpd @ 0 xor  xpd !
     xqd @ 0 xor  xqd !
     xrd @ 0 xor  xrd !
     xsd @ 0 xor  xsd !
     xtd @ 0 xor  xtd !
     xud @ 0 xor  xud !
     xvd @ 0 xor  xvd !
     xwd @ 0 xor  xwd !
     xxd @ 0 xor xxd !
     xyd @ 0 xor  xyd !
     xzd @ 0 xor xzd !
     sp1x @ 0 xor sp1x !
     sp2x @ 0 xor sp2x !
               ;
: gxx1     ( n1 - n2 )  \ Last DATA DIGIT
     xad @ 0 xor  xad !
     xbd @ 0 xor  xbd !
     xcd @ 0 xor  xcd !
     xdd @ 0 xor  xdd !
     xed @ 0 xor  xed !
     xfd @ 0 xor  xfd !
     xgd @ 1 xor  xgd !
     xhd @ 0 xor  xhd !
     xid @ 0 xor  xid !
     xjd @ 0 xor  xjd !
     xkd @ 0 xor  xkd !
     xld @ 0 xor  xld !
     xmd @ 0 xor  xmd !
     xnd @ 0 xor  xnd !
     xod @ 0 xor  xod !
     xpd @ 0 xor  xpd !
     xqd @ 0 xor  xqd !
     xrd @ 0 xor  xrd !
     xsd @ 0 xor  xsd !
     xtd @ 0 xor  xtd !
     xud @ 0 xor  xud !
     xvd @ 0 xor  xvd !
     xwd @ 0 xor  xwd !
     xxd @ 0 xor xxd !
     xyd @ 0 xor  xyd !
     xzd @ 0 xor xzd !
     sp1x @ 0 xor sp1x !
     sp2x @ 0 xor sp2x !
               ;
: hxx1     ( n1 - n2 )  \ Last DATA DIGIT
     xad @ 0 xor  xad !
     xbd @ 0 xor  xbd !
     xcd @ 0 xor  xcd !
     xdd @ 0 xor  xdd !
     xed @ 0 xor  xed !
     xfd @ 0 xor  xfd !
     xgd @ 0 xor  xgd !
     xhd @ 1 xor  xhd !
     xid @ 0 xor  xid !
     xjd @ 0 xor  xjd !
     xkd @ 0 xor  xkd !
     xld @ 0 xor  xld !
     xmd @ 0 xor  xmd !
     xnd @ 0 xor  xnd !
     xod @ 0 xor  xod !
     xpd @ 0 xor  xpd !
     xqd @ 0 xor  xqd !
     xrd @ 0 xor  xrd !
     xsd @ 0 xor  xsd !
     xtd @ 0 xor  xtd !
     xud @ 0 xor  xud !
     xvd @ 0 xor  xvd !
     xwd @ 0 xor  xwd !
     xxd @ 0 xor xxd !
     xyd @ 0 xor  xyd !
     xzd @ 0 xor xzd !
     sp1x @ 0 xor sp1x !
     sp2x @ 0 xor sp2x !
               ;
: ixx1     ( n1 - n2 )  \ Last DATA DIGIT
     xad @ 0 xor  xad !
     xbd @ 0 xor  xbd !
     xcd @ 0 xor  xcd !
     xdd @ 0 xor  xdd !
     xed @ 0 xor  xed !
     xfd @ 0 xor  xfd !
     xgd @ 0 xor  xgd !
     xhd @ 0 xor  xhd !
     xid @ 1 xor  xid !
     xjd @ 0 xor  xjd !
     xkd @ 0 xor  xkd !
     xld @ 0 xor  xld !
     xmd @ 0 xor  xmd !
     xnd @ 0 xor  xnd !
     xod @ 0 xor  xod !
     xpd @ 0 xor  xpd !
     xqd @ 0 xor  xqd !
     xrd @ 0 xor  xrd !
     xsd @ 0 xor  xsd !
     xtd @ 0 xor  xtd !
     xud @ 0 xor  xud !
     xvd @ 0 xor  xvd !
     xwd @ 0 xor  xwd !
     xxd @ 0 xor xxd !
     xyd @ 0 xor  xyd !
     xzd @ 0 xor xzd !
     sp1x @ 0 xor sp1x !
     sp2x @ 0 xor sp2x !
               ;
: jxx1     ( n1 - n2 )  \ Last DATA DIGIT
     xad @ 0 xor  xad !
     xbd @ 0 xor  xbd !
     xcd @ 0 xor  xcd !
     xdd @ 0 xor  xdd !
     xed @ 0 xor  xed !
     xfd @ 0 xor  xfd !
     xgd @ 0 xor  xgd !
     xhd @ 0 xor  xhd !
     xid @ 0 xor  xid !
     xjd @ 1 xor  xjd !
     xkd @ 0 xor  xkd !
     xld @ 0 xor  xld !
     xmd @ 0 xor  xmd !
     xnd @ 0 xor  xnd !
     xod @ 0 xor  xod !
     xpd @ 0 xor  xpd !
     xqd @ 0 xor  xqd !
     xrd @ 0 xor  xrd !
     xsd @ 0 xor  xsd !
     xtd @ 0 xor  xtd !
     xud @ 0 xor  xud !
     xvd @ 0 xor  xvd !
     xwd @ 0 xor  xwd !
     xxd @ 0 xor xxd !
     xyd @ 0 xor  xyd !
     xzd @ 0 xor xzd !
     sp1x @ 0 xor sp1x !
     sp2x @ 0 xor sp2x !
               ;
